### ISSUE TITLE
name and expiry date

### ISSUE THREAD

**Issue by iKhan1057** [getbouncer/cardscan-android#82]
Guys can you help me if there is possibility to get name of the card holder(if there) and expiry date.

**Comment by awushensky** [comment]
Hi @iKhan1057 , we're currently working on adding support for both of these! We roughly estimate we'll have them implemented by 2020 Q2

**Comment by valeriandema** [comment]
Hi @awushensky! we are about to decide what tools to choose for scanning bank cards and we enjoy working your cardscan! the only thing that confuses is detecting expiry date. it was said it's needed 1-2 months to solve the issue, so could you please give an estimated time of resolving? sorry for asking the same question guys, but it's important for us

**Comment by awushensky** [comment]
Hi @valeriandema, we're actively working on expiry date. At this point it looks like it will be another 1 to 2 months before it's usable, an another few months after that before it's as reliable as number detection. We've been focusing on improving performance with our detection models and this slipped as a result.

**Comment by valeriandema** [comment]
> Hi @valeriandema, we're actively working on expiry date. At this point it looks like it will be another 1 to 2 months before it's usable, an another few months after that before it's as reliable as number detection. We've been focusing on improving performance with our detection models and this slipped as a result.

thank you @awushensky !

**Comment by awushensky** [comment]
Hi @valeriandema , sorry for the delay, we have released version 2.0.0014 which contains name and expiry scanning. Please see the documentation for details: https://docs.getbouncer.com/card-scan/android-integration-guide

**Comment by mihirmodiofficial** [comment]
i still cannot extract month and year everytime. only sometime it extracts month and year and that to be wrong.

using sdk version: - com.getbouncer:cardscan-ui:2.0.0059

set initializeNameAndExpiryExtraction to true
